"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var user_1 = require("../../controllers/user");
var userRegister_1 = require("../../middlewares/zod/userRegister");
var userLogin_1 = require("../../middlewares/zod/userLogin");
var zodValidaate_1 = require("../../middlewares/Auth/zodValidaate");
var verifyOtp_1 = require("../../middlewares/zod/verifyOtp");
var resendOtp_1 = require("../../middlewares/zod/resendOtp");
var router = (0, express_1.Router)();
router.post('/user/register', (0, zodValidaate_1.zodValidate)(userRegister_1.SignUpZ), user_1.Register);
router.post('/user/resendOtp', (0, zodValidaate_1.zodValidate)(verifyOtp_1.VerifyOtpZ), user_1.resendOtp);
router.post('/user/verifyOtp', (0, zodValidaate_1.zodValidate)(resendOtp_1.ResendOtpZ), user_1.verifyOtp);
router.post('/user/login', (0, zodValidaate_1.zodValidate)(userLogin_1.LoginZ), user_1.Login);
router.post('/user/forget-password', user_1.forgetPassword);
router.post('/user/rest-password', user_1.resetPassword);
exports.default = router;
